// <auto-generated />
namespace MFGroup.PrintingControl.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PrimeiraMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrimeiraMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201307151955254_PrimeiraMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
